services:
  varnish:
    build:
      context: ../
      dockerfile: ./debug/Dockerfile
    command: /entrypoint.sh
    ports:
      - 8080:80
    environment:
      - VARNISH_SIZE=200M
    volumes:
      - ./default.vcl:/etc/varnish/default.vcl
      - ./entrypoint.sh:/entrypoint.sh
  nginx:
    image: nginx:1.27-alpine
    ports:
      - 8081:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
